"""rename indexes from peewee -> sqla

Revision ID: f56e092a754c
Revises: cc17c70b259a
Create Date: 2023-05-20 18:38:07.528812

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "f56e092a754c"
down_revision = "cc17c70b259a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("gamesession_user_id", table_name="gamesession")
    op.create_index(
        op.f("ix_gamesession_user_id"), "gamesession", ["user_id"], unique=False
    )
    op.drop_index("turn_gamesession_id", table_name="turn")
    op.create_index(
        op.f("ix_turn_gamesession_id"), "turn", ["gamesession_id"], unique=False
    )
    op.drop_index("turnlog_turn_id", table_name="turnlog")
    op.create_index(op.f("ix_turnlog_turn_id"), "turnlog", ["turn_id"], unique=False)
    op.drop_index("user_username", table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("user_username", "user", ["username"], unique=False)
    op.drop_index(op.f("ix_turnlog_turn_id"), table_name="turnlog")
    op.create_index("turnlog_turn_id", "turnlog", ["turn_id"], unique=False)
    op.drop_index(op.f("ix_turn_gamesession_id"), table_name="turn")
    op.create_index("turn_gamesession_id", "turn", ["gamesession_id"], unique=False)
    op.drop_index(op.f("ix_gamesession_user_id"), table_name="gamesession")
    op.create_index("gamesession_user_id", "gamesession", ["user_id"], unique=False)
    # ### end Alembic commands ###
